### ISSUE TITLE
Conda environment setup fails due to GCC missing

### ISSUE THREAD

**Issue by aretasg** [IBM/depiction#63]
Hi,

I have attempted to create a conda environemnt from the environment.yml and had an issue with some packages installing due to GCC not listed in the file. Adding GCC as a requirement in environment.yml has solved the issue on WSL Ubuntu:
  - gcc_linux-64=7.3.0
  - gxx_linux-64=7.3.0

Note you will probably need different versions of GCC for other OS than Linux.

**Comment by C-nit** [comment]
Thanks for reporting this and finding a fix for your case.

Can you tell which packages were failing? Specifically, does it fail on installation of `rdkit` or later on a pip package?

This is a bit hard to debug for us since even the linux version on travis comes with gcc.

**Comment by aretasg** [comment]
Yes, it failed due to rdkit.
